name: Build Docker Image

on:
  push:
    tags:
      - 'v*'  # Триггерится при создании тега с префиксом 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

        
      - name: Build the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/green-api:latest
          secrets: |
            private_key=${{ secrets.PRIVATE_KEY }}
            certificate=${{ secrets.CERTIFICATE }}

      - name: Log out of the GitHub Container Registry
        if: ${{ steps.build.outputs.image_id }}
        run: |
          echo "Logging out of GHCR for ${{ steps.build.outputs.registry }}..."
          docker logout ghcr.io
