name: Build Docker Image

on:
  push:
    tags:
      - 'v*'  # Триггерится при создании тега с префиксом 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
          driver-type: overlay2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_USER }}
          password: ${{ secrets.CR_PAT }}

        
      - name: Build the Docker image
        id: build
        uses: docker//build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            latest
            ${{ github.event.repository.release.tag_name }}

      - name: Log out of the GitHub Container Registry
        if: ${{ steps.build.outputs.image_id }}
        run: |
          echo "Logging out of GHCR for ${{ steps.build.outputs.registry }}..."
          docker logout ghcr.io
